export const FETCH_WEATHER_READINGS = 'FETCH_WEATHER_READINGS'
export const FETCH_WEATHER_READINGS_SUCCESS = 'FETCH_WEATHER_READINGS_SUCCESS'
export const FETCH_WEATHER_READINGS_FAILURE = 'FETCH_WEATHER_READINGS_FAILURE'